### ISSUE TITLE
[UNREAL] CI/CD Pipeline

### ISSUE THREAD

**Issue by Leinnan** [beamable/UnrealSDK#27]
# Unreal CI/CD Workflows

- Single Project Repo (Samples and OnlineSubsystemBeamable live in the same UnrealProject repo)
- Organic Code Reviews (no PRs on non-release branches, ask for code reviews as needed instead)

## CLI Bundling and Version Compatibility

- Our repo will have a file inside the .beamable folder named "version.compat.txt" whose only content is the SemVer for the CLI package associated with the UE version.
- We'll have a ".beamable/utilities/customerProjectSetup.sh/ps1" and a ".beamable/utilities/getCLI.sh/ps1" scripts that live inside the .beamable folder. The first script is what customers should run after importing beamable into their project. The second is called by the first one to fetch the CLI and install/update it locally.
- The UE CLI integration will allow you to configure a per-developer "path override" for a CLI (this is mostly so that we can point our UE Editor to the executables built locally inside our cloned BeamableProduct repo while developing the CLI itself).
  - We should also build and share some Rider Run Configuration templates to make it easier to debug and develop the CLI while inside customer projects and/or our own.
- Our release testing automation should run these scripts and verify that the installed CLI version matches that of the text file.

## On GitHub Actions, PR and workflow

- We won't be developing using GitFlow and we'll definitely not be doing branch-per-task PRs.
- We have a forward-branching workflow (Naughty Dog and Insomniac also do this, if you need big names to accept this)
- `Dev`, `Version X.Y-Release` and `Version X.Y-Hotfix-<JIRA-TICKET-#1>-[<JIRA-TICKET-#2>]` are the only branches that exist.
  - Fixes for older versions branch off from its "Version X.Y-Release" branch and forward ported by the person who fixed it into "Dev".
- New Feature Development happens on "Dev", behind a feature flag if it requires multiple commits to dev to get it to work. 
  - We should make an EngineSubsystem that handles FName-based runtime-feature flags.
  - If there's urgent demand for new features in some older version, this manually backported to the oldest version that will be needed; and then forward ported WHILE TESTING IT.
  - The feature flag in older versions would be always FALSE by default, so it never changes behavior.

### What are feature flags?
- These are just a short version of "EVERY CODE THAT IS A PART OF THIS FEATURE EXISTS BEHIND AN IF-STATEMENT ON A CONFIGURABLE FLAG".
  - There are compile time flags (typically enforced at the build system level).
  - There are runtime flags (typically enforced by a simple system wrapping a dictionary of keys -> bools).

### What about Unit Tests?

- Our lower level libraries do have Unit Tests (and we need to go back to full coverage on those).
- We do not want to have full test coverage on all `RuntimeSubsystems` only Engine Subsystems and library-like functionality (serialization pipelines, etc...). 
  - We might want to look into BP-based tests for the most common operations of each `RuntimeSubsystem`, though. 
- We do need to run builds/tests for every commit on "Version X.Y-???" branches. Dev, however, should only run once a day in its nightly build. People should run them manually through Session FrontEnd and we should set up a nightly build run just to catch egregious mistakes. 

# Releases

- Releases are much simpler in UE since install flow is that game-makers do one of two things:
  - Clone the `Version X.Y-Release` public branch and copy/paste the following files:
    - `Plugins/BeamableCore` into their Plugins directory.
    - `.beamable/utilities` into their root project directory.
  - Download the release’s zip file and unzip it in their project’s root directory.
  - In a future release, we'll want to support download through the marketplace. THIS IS NOT FOR 1.0.0.
- For now, the release of one or more `Version-X.Y-Hotfix` branches are is:
  - Make sure all samples are building and, if they have any, their tests are passing.
  - Make sure all project tests are passing.
  - Merge one or more Version X.Y-Hotfix into Version X.Y-Release.
  - Tag the new head of the branch with "X.Y.Z" incrementing Z from the previous tag.
  - This should trigger another commit, with a X.Y.Z-Release tag, that enforces a few things:
    - `Engine.ini` now has `BeamableCore`'s Prod environment instead of its Dev environment (so people that clone and run our main repo can log in with their own accounts)
    - Package up a `zip` file release without samples for people that don't want to clone the repo and instead just want to unzip things into the Plugins folder. Set it up in GitHub releases.
   - Update GitHub wiki/Readme with Unreal docs that are in the project.
- For now, the release of a new "Version-X.Y" is:
  - Same as the above, except we are creating a new branch `Version X.Y-Release` from Dev instead of merging various hotfixes (this is effectively “making an RC“).
- After each of the releases above, we should close the GitHub milestone manually, moving any incomplete tickets to a future reasonable milestone.

## Forward Porting Hotfixes
- After a release, if you want the fix forward propagated; do that manually and test it.
- You can try to merge the hotfix branch into dev, but... if Dev is the next major version, there might be braking changes there. 
- If its a minor version, then you should be able to do it rather easily.
- As the person responsible for the fix, you can choose to delay forward porting it to our `dev` branch until the next Minor/Major release.

## Obsolete and Breaking Changes

- We do not cause breaking changes in Hotfix branches OR in Dev (when the next is a minor release).
- We DO mark things as obsolete in Hotfix and/or Minor Releases; ONLY IF, the replacing feature will be released in the next version (minor or major).
- We DO delete ALL Obsolete marked functions every major version and as soon as possible.

## Sample Project Development and Release Workflows
- Each sample specific code and content lives inside its own plugin that depends on the `BeamableCore` and, optionally, `OnlineSubsystemBeamable`.
- Each Samples Folder has a Starting Level named `Sample_<SampleName>` and, for dedicated servers, a `Sample_<SampleName>_Server`.
- Our build pipeline needs to know how to generate a build that contains all the assets in a samples plugin and starts at the `Sample_<SampleName>` level.
- For non-dedicated server builds of any samples, we need to be able to run build locally and easily (press a button/run a script and get the build).
  - We only need Linux Dedicated Server builds --- but we need Windows/Linux client builds (in the future, we'll need all platform builds).

## OnlineSubsystemBeamable Development and Release (applies to any optional complementary plugin).
- The releases for this plugin are tied to the raw SDKs version numbering.
- This is just another build artifact triggered by the tagging of release branches with "X.Y.Z" tag.

## Working in Customer Repos
- Because the Plugin's code is not read-only; professional services deal in UE will work directly in the customer repo.
- The developer working in it is responsible for bringing hotfixes he makes into the `BeamableUnreal` repo.
- Doing so, it should apply the solution as described. If it is a hotfix, make a branch --- if its a "next-Minor/Major milestone" release change, get it into `dev`.
  - In this case, the commit with the changes should AS GRANULAR AS POSSIBLE so that other professional services developers may cherry-pick them into their customers own versions until that milestone gets shipped out.

# Resources: 
- [Unreal Containers](https://unrealcontainers.com/)
- [Building Unreal Engine](https://docs.unrealengine.com/4.27/en-US/ProductionPipelines/DevelopmentSetup/BuildingUnrealEngine/)
- [Setting Up Dedicated Servers](https://docs.unrealengine.com/4.27/en-US/InteractiveExperiences/Networking/HowTo/DedicatedServers/)
- [Windows Builds/Containers](https://docs.unrealengine.com/4.27/en-US/SharingAndReleasing/Containers/HowTo/BuildingTheWindowsContainerImagesFromSource/)

**Comment by PedroRauizBeamable** [comment]
The build pipeline ended up looking a bit different than what is described here --- docs incoming in later weeks.
