### ISSUE TITLE
[UNREAL] Improve LiveOps demo

### ISSUE THREAD

**Issue by cdhanna** [beamable/UnrealSDK#41]
This depends on https://github.com/beamable/UnrealSDK/issues/43

We need to:

- Add an Item Content called `sample_item` that has some text properties we can display in a section of the `LiveOpsUI` widget. Also, add a display that shows the default `currency.coins` and `currency.gems`.
- Add a `LiveOpsDemoMs` that has a `PrepareNewPlayer` ClientCallable (that sets up a `game.private` numerical stat for the player and a few `sample_item` instances to that player inventory), a `IncrementStat` ClientCallable (that increments that stat) and a `UpgradeItem` (that increments the level of an item). This microservice should have the `BeamServiceGroup` tag of `BEAMPROJ_LiveOpsDemo`.
  - The `sample_item` instances should have a `item_level` in its key/value pairs.
- Expose buttons next to the Stat and the Items that invoke the `IncrementStat` and `UpgradeItem`.
- Configure Announcements, with no expiration date, in the portal for this realm that are segmented based on that `game.private` stat.
  - There should be at least one announcement that grants currencies as a gift, one that grants another `sample_item` as a gift and another that 
- Add an `Open` button to each announcement display that shows a pop-up displaying the gifts, if any, and a `Claim` button. This pop-up should also mark this announment as `Read` (the announcement list should show an indicator when its read). For reference:
  - ![Image](https://github.com/beamable/UnrealSDK/assets/92586258/c08d7b7c-c917-4a69-b45d-f69ea80d3104)

---

Then, write up this sample docs so that a user can set it up and use it. Use the other ones as a reference for how to write this.

**Comment by PedroRauizBeamable** [comment]
Done
