### ISSUE TITLE
[UNREAL] Re-work Microservice Window - Part 1

### ISSUE THREAD

**Issue by Leinnan** [beamable/UnrealSDK#44]
The Microservice Window should be a Tab-based window.

Make a Summary tab containing thin cards that sumarize the Microservice. For now, it should have:
- BeamoId
- Button for Running Locally with Docker (should be disabled if the service is running in docker)
- Button for Running Locally as Standalone (should be disabled if the service is running as standalone)
- Display on whether or not the service is deployed and/or running in the realm currently pointed at.

Here's a rough draft:
![Image](https://github.com/user-attachments/assets/c43c0705-bab7-4ef4-b0cb-1a800830375e)

---

The individual service tabs should, for now, have the same stuff as the summary. PLUS, it should a large diagnostics window:
![Image](https://github.com/user-attachments/assets/a1d18881-6150-4c58-9ed3-2e3e288ed443)

The image above is mostly a way to describe where we are heading. For now, focus on just getting the logs in there. We might need a new CLI command that streams out those logs as we DON'T want to only have logs when the service is started from the editor. In UE, a very common workflow is to start the service through the Microservice SLN itself and then open/close the editor several times over the service's runtime. If logs don't work for manually started services, they're not all that useful. Talk to @cdhanna about a way to do this in the CLI (I _think_ there's a logs command already, but... we need it to be a bit more "discovery" focused).

Keep in mind, we want to start/close the stream of logs with per-service granularity. Something like, `beam project logs -w MyService` (It'd be nice if you could optionally pass in a gamertag, in which case the command would attach to the log stream of a running service of that developer --- but... its not necessary for now) . To do this, add a `AttachToServiceLogs` function to the Microservice Editor system that calls this `CliCommand` and stores it. When the window is closed OR the service turns itself off, detach it,

--- 

The goal of this ticket is to reorganize the Microservice Window to be a bit more useful when in the editor. First, do this. Part 2 is about integrating with the local federation stuff.

**Comment by PedroRauizBeamable** [comment]
Done (UX ended up a bit different after testing and usage)
