### ISSUE TITLE
UNREAL - Create Store Subsystem with support for buying items with currencies

### ISSUE THREAD

**Issue by PedroRauizBeamable** [beamable/UnrealSDK#46]
We need a `UBeamStoreSubsystem` (inherit from`UBeamRuntimeSubsystem`) and content definitions for `Stores` and `Listings`.

The subsystem should keep a local cache of existing stores. We should expose a `StoresToKeepRefreshed` list of `FBeamContentId` inside `UBeamRuntimeSettings` so that customers can specify which stores we should prefetch. This array being empty, we should pre-fetch all stores. This fetching should happen after the initial content refresh (in the `OnBeamableContentReady` callback for `UBeamRuntimeSubsystem`).

After initialization, the subsystem exposes the operations to do the following:
- `PurchaseListingOperation`: 
  - Attempts to purchase a listing.
  - Before making the request, validate that the listing and store exists failing the operation with respective errors.
  - If valid listing and store, make the request.
  - If the request is successful, use `UBeamInventorySubsystem` functions to manually and immediately update the inventory state locally such before completing the operation successfully.
  - If the request fails, fail the operation with the error.
 
- `RefreshStore`:
  - This is just a "fetch stuff again" operation. 

It should also provide the following utility functions:
- `TryGetItemFromListing`: Returns one or more Item content inside a listing if any.
- `TryGetCurrencyFromListing`: Returns one or more currency+amount from inside a listing if any.
- `GetFormattedPrice`: Returns a formated string for the price of a particular listing.

I don't really see any value in exposing callbacks for this system so let's try not add any just yet and see if the need arises.

---
Bonus Goal:
- If we can make a little pagination helper struct and a set of functions that operate on the struct that would be helpful.
- Something like `CreateStorePages(int pageSize, bool isCyclical)` that returns a `FBeamStorePages` with `PageSize`, `CurrentPage`, `TotalPages`, `CurrentListings`, `StoreContentId` and `IsCyclical`.
- Then have a bunch of functions in the `UBeamStoreSubsystem` that `NextPage` and `PreviousPage` (with wrap-around) that advance/revert the current page and fill out the correct listing based on the given `pageSize`.

This would be a nice little helper for people to implement paged UIs. DO NOT MAKE THIS CALLBACK-BASED OR WITH UOBJECTS.

**Comment by Leinnan** [comment]
Work done, I did not do the bonus part, I think it would be for the best to do it as first part of creating UI example instead.
